# Generated by Django 4.1.7 on 2023-02-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageOrders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='Orders',
        ),
    ]
